spring.application.name=maquetado
mensaje.application="Aplicacion Web con Spring"

#configuracion thymeleaf
spring.thymeleaf.prefix=classpath:/paginas/
spring.thymeleaf.suffix=.html
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/proyecto
spring.datasource.username=root
spring.datasource.password=MSqlDB

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
